version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis    #标明镜像ID,本地如果没有会尝试pull下来

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:      # 加入环境变量
    - REDIS_HOSTS=local:redis:6379
    ports:            # 暴露端口
    - 8081:8081
  

  mysql:
    image: mysql:5.7
    volumes:            # 挂载路径，文件映射
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:          
      MYSQL_ROOT_PASSWORD: xccloud
      MYSQL_DATABASE: xccloud
      MYSQL_USER: xccloud
      MYSQL_PASSWORD: xccloud
    ports:
    - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8000:80"
    depends_on:           # 服务间依赖关系
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: xccloud
      PMA_PASSWORD: xccloud

  backend:
    image: java:8-jre
    ports:
      - "4000:8080"
    depends_on:
      - mysql

  nginx:
    image: nginx:1.15
    volumes:
      - ../web-weixin/dist:/usr/share/nginx/html/web-weixin
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - backend
